{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:  
  name: practicaserver
spec:
  rules:
   - host:  {{ .Values.host.name }} 
     http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: serverservice
            port:
              number: 8080
{{ end }}